
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - github-prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@github-prod

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@github-prod
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        BASE_BRANCH: github-prod
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
